name: qnkat-playground

dependencies:
  - base
  - containers
  - more-containers
  - diagrams-lib
  - ihaskell-diagrams
  - diagrams-cairo
  - QuickCheck

library:
  exposed-modules:
    - QNKAT.Drawing
    - QNKAT.Definitions
    - QNKAT.UnorderedTree
    - QNKAT.Test
