name: qnkat-playground

default-extensions:
  - DerivingStrategies
  - TypeFamilies
  - GeneralizedNewtypeDeriving
  - FunctionalDependencies
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-incomplete-uni-patterns
  - -fwarn-missing-deriving-strategies

dependencies:
  - base
  - containers
  - more-containers
  - diagrams-lib
  - ihaskell-diagrams
  - diagrams-cairo
  - QuickCheck
  - fixed-vector

library:
  source-dirs: src
  exposed-modules:
    - QNKAT.Drawing
    - QNKAT.Definitions
    - QNKAT.Definitions.Core
    - QNKAT.Definitions.Structures
    - QNKAT.Definitions.Policy
    - QNKAT.Definitions.OneStepHistoryQuantum
    - QNKAT.Definitions.TimelyHistoryQuantum
    - QNKAT.Definitions.StepHistoryQuantum
    - QNKAT.Definitions.HistoryQuantum
    - QNKAT.UnorderedTree
    - QNKAT.ChoiceUtilities
    - QNKAT.DSL
    - QNKAT.Test

tests:
  spec: 
    main: Spec
    source-dirs: 
      - test
      - src
    dependencies: 
      - hspec
