name: qnkat-playground

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-incomplete-uni-patterns
  - -fwarn-missing-deriving-strategies

dependencies:
  - base
  - containers
  - more-containers
  - diagrams-lib
  - ihaskell-diagrams
  - diagrams-cairo
  - QuickCheck

library:
  source-dirs: src
  exposed-modules:
    - QNKAT.Drawing
    - QNKAT.Definitions
    - QNKAT.UnorderedTree
    - QNKAT.ChoiceUtilities
    - QNKAT.DSL
    - QNKAT.Test

tests:
  spec: 
    main: Spec
    source-dirs: 
      - test
      - src
    dependencies: 
      - hspec
